name: Deploy Portfolio Website

on:
  push:
    branches:
      - main  # Trigger deployment when changes are pushed to the main branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # Use the latest version of Ubuntu for the runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Check out your code

    - name: Set up Node.js
      uses: actions/setup-node@v2  # Set up Node.js environment (if your website uses Node.js)

      with:
        node-version: '14'  # You can specify the version of Node.js (or skip this if not required)

    - name: Install dependencies
      run: |
        npm install  # Install project dependencies (skip this if your website doesn't use npm)

    - name: Build website
      run: |
        npm run build  # Run build command (replace with the correct build command for your website)

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3  # GitHub Action to deploy to GitHub Pages
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Use the automatically provided GitHub token
        publish_dir: ./build  # Directory to publish (replace with your actual build directory)
